name: 'Space Shooter GIF Generator'
description: 'Transform your GitHub contribution graph into an animated space shooter game GIF for your README'
author: 'yiweishen'

branding:
  icon: 'zap'
  color: 'purple'

inputs:
  github-token:
    description: 'GitHub token for fetching contribution data (usually secrets.GITHUB_TOKEN)'
    required: true
  username:
    description: 'GitHub username to generate game for (defaults to repository owner)'
    required: false
    default: ${{ github.repository_owner }}
  output-path:
    description: 'Path where the GIF should be saved'
    required: false
    default: 'gh-space-shooter.gif'
  strategy:
    description: 'Enemy clearing strategy: column (left to right), row (top to bottom), or random'
    required: false
    default: 'random'
  fps:
    description: 'Frames per second for generation (higher = smoother but larger file)'
    required: false
    default: '40'
  output-fps:
    description: 'Output FPS after optimization (lower = smaller file, default: 10)'
    required: false
    default: '10'
  max-colors:
    description: 'Maximum colors in optimized GIF palette (lower = smaller file, default: 64)'
    required: false
    default: '64'
  commit:
    description: 'Whether to commit and push the generated GIF (default: true)'
    required: false
    default: 'true'
  commit-message:
    description: 'Commit message for the GIF update'
    required: false
    default: 'Update space shooter game GIF'
  target-branch:
    description: 'Target branch to push the GIF to (defaults to current branch)'
    required: false
    default: 'space-shooter-gif'

outputs:
  gif-path:
    description: 'Path to the generated GIF file'
    value: ${{ inputs.output-path }}
  gif-size:
    description: 'Size of the generated GIF in bytes'
    value: ${{ steps.optimize.outputs.size }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install gh-space-shooter

    - name: Generate raw GIF
      id: generate
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        gh-space-shooter ${{ inputs.username }} \
          --output raw_game.gif \
          --strategy ${{ inputs.strategy }} \
          --fps ${{ inputs.fps }}
        echo "Generated raw GIF:"
        ls -lh raw_game.gif

    - name: Install ffmpeg
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Optimize GIF with ffmpeg
      id: optimize
      shell: bash
      run: |
        # Generate optimized palette
        ffmpeg -y -i raw_game.gif \
          -vf "fps=${{ inputs.output-fps }},palettegen=max_colors=${{ inputs.max-colors }}:stats_mode=diff" \
          palette.png

        # Apply palette with ordered dithering for smaller file size
        ffmpeg -y -i raw_game.gif -i palette.png \
          -filter_complex "fps=${{ inputs.output-fps }}[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3" \
          "${{ inputs.output-path }}"

        # Clean up temporary files
        rm -f raw_game.gif palette.png

        # Output file size
        SIZE=$(stat -c%s "${{ inputs.output-path }}" 2>/dev/null || stat -f%z "${{ inputs.output-path }}")
        echo "size=$SIZE" >> $GITHUB_OUTPUT
        echo "Optimized GIF size: $(ls -lh "${{ inputs.output-path }}" | awk '{print $5}')"

    - name: Commit and push GIF
      if: ${{ inputs.commit == 'true' }}
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add "${{ inputs.output-path }}"
        git diff --staged --quiet || git commit -m "${{ inputs.commit-message }}"
        if [ -n "${{ inputs.target-branch }}" ]; then
          git push origin HEAD:${{ inputs.target-branch }}
        else
          git push
        fi
